
all: templatex varArgsx lab9cx lab9cppx

templatex:	template.cpp
	g++ -o templatex template.cpp

varArgsx:	varArgs.c
	gcc -o varArgsx varArgs.c

lab9cppx:	lab9.cpp
	g++ -o lab9cppx lab9.cpp

lab9cx:	lab9.c
	gcc -o lab9cx lab9.c

clean:
	rm -f varArgsx templatex lab9cx lab9cppx

