
CC = gcc -Wall
EXEs = lab7a lab7b lab7c lab7d lab7e lab7f lab7g lab7h lab7i lab7j lab7k lab7L
all: ${EXEs}

lab7a: lab7a.c
	${CC} lab7a.c -o lab7a

lab7b: lab7b.c
	${CC} lab7b.c -o lab7b -lm

lab7c: lab7c.c
	${CC} lab7c.c -o lab7c

lab7d: lab7d.c
	${CC} lab7d.c -o lab7d

lab7e: lab7e.c
	${CC} lab7e.c -o lab7e

lab7f: lab7f.c
	${CC} lab7f.c -o lab7f

lab7g: lab7g.c
	${CC} lab7g.c -o lab7g

lab7h: lab7h.c
	${CC} lab7h.c -o lab7h

lab7i: lab7i.c
	${CC} lab7i.c -o lab7i

lab7j: lab7j.c
	${CC} lab7j.c -o lab7j

lab7k: lab7k.c
	${CC} lab7k.c -o lab7k

lab7L: lab7L.c
	${CC} lab7L.c -o lab7L

clean:
	rm -f ${EXEs}

